/**
 * Protocol ID define here by enum class
 * This file is generated by Python script. Do not edit!!!
 * Generated time: 2024-10-22 19:44:13
 * Python version: v3.12.7
 * Script version: v0.1
 */

#pragma once

#include <cstdint>

namespace protocol {
	enum class ProtoType : uint32_t {
		// Login
		CS_LoginRequest = 1001,
		SC_LoginResponse = 1002,
		SC_OverrideLoginResponse = 1003,

		// Appearance
		CS_AppearanceRequest = 2001,
		SC_AppearanceResponse = 2002,

		PROTO_TYPE_MAX,
	}; // ProtoType
} // protocol