/**
 * Protocol callback function define here.
 * This file is generated by Python script. Do not edit!!!
 * Generated time: 2024-10-18 12:49:31
 * Python version: v3.12.7
 * Script version: v0.1
 */

#pragma once

#include <memory>

namespace base {
	class Package;
	class Player;
	using ConnectionPointer = std::shared_ptr<class Connection>;
}

namespace protocol {

	// Login

	// Appearance
	void CS_AppearanceRequest(const std::shared_ptr<base::Player> &plr, base::Package *pkg);

} // protocol