/**
 * Register protocol callback to base::UProtocolSystem
 * This file is generated by Python script. Do not edit!!!
 * Generated time: 2024-10-21 22:06:48
 * Python version: v3.12.7
 * Script version: v0.1
 */

#include "Protocol.generated.h"
#include "ProtoType.generated.h"

#include "../src/system/protocol/ProtocolSystem.h"

void base::ProtocolSystem::RegisterProtocol() const {
	using namespace protocol;
	// Login

}