/**
 * Protocol ID define here by enum class
 * This file is generated by Python script. Do not edit!!!
 * Python version: v3.12.7
 * Script version: v0.1
 */

#pragma once

#include <cstdint>

namespace protocol {
	enum class ProtoType : uint32_t {
		// Login
		CS_LoginRequest = 1001,
		SC_LoginResponse = 1002,
		SC_OverrideLoginResponse = 1003,

		// Appearance
		CS_AppearanceRequest = 2001,
		SC_AppearanceResponse = 2002,

		PROTO_TYPE_MAX,
	}; // ProtoType

	constexpr const char* ProtoTypeToString(const ProtoType value) {
		switch (value) {
			case ProtoType::CS_LoginRequest: return "CS_LoginRequest";
			case ProtoType::SC_LoginResponse: return "SC_LoginResponse";
			case ProtoType::SC_OverrideLoginResponse: return "SC_OverrideLoginResponse";
			case ProtoType::CS_AppearanceRequest: return "CS_AppearanceRequest";
			case ProtoType::SC_AppearanceResponse: return "SC_AppearanceResponse";
			default: return "UNDEFINED";
		} // switch
	}

} // protocol