/**
 * Protocol callback function define here.
 * This file is generated by Python script. Do not edit!!!
 * Generated time: 2024-10-21 10:39:04
 * Python version: v3.12.7
 * Script version: v0.1
 */

#pragma once

#include <memory>

namespace base {
	class Package;
	class Player;
	using ConnectionPointer = std::shared_ptr<class Connection>;
}

namespace protocol {

	// Login

} // protocol