/**
 * Protocol callback function define here.
 * This file is generated by Python script. Do not edit!!!
 * Generated time: 2024-10-23 02:17:41
 * Python version: v3.12.7
 * Script version: v0.1
 */

#pragma once

#include <asio.hpp>
#include <memory>

namespace base {
	class Package;
	using ConnectionPointer = std::shared_ptr<class Connection>;
}

class Player;

namespace protocol {

	 using asio::awaitable;

	// Login

	// Appearance
	awaitable<void> CS_AppearanceRequest(const std::shared_ptr<Player> &plr, base::Package *pkg);

} // protocol