/**
 * Protocol callback function define here.
 * This file is generated by Python script. Do not edit!!!
 * Python version: v3.12.7
 * Script version: v0.1
 */

#pragma once

#include <asio.hpp>
#include <memory>

class IPackage;
using AConnectionPointer = std::shared_ptr<class UConnection>;
class ICharacter;

namespace protocol {

	 using asio::awaitable;

	// Login

} // protocol

#include "ProtoType.gen.h"
#include "../../src/system/protocol/ProtocolSystem.h"

inline void LoadProtocol(UProtocolSystem *sys) {

	using namespace protocol;

	// Login

}