#pragma once

/**
 * Protocol ID define here by enum class
 * This file is generated by Python script. Do not edit!!!
 * Python version: v3.12.7
 * Script version: v0.1
 */

#include <cstdint>

namespace protocol {
	enum class EProtoType : uint32_t {
		// Login
		CS_LoginRequest = 1001,
		SC_LoginResponse = 1002,
		SC_OverrideLoginResponse = 1003,

		// Appearance
		CS_AppearanceRequest = 2001,
		SC_AppearanceResponse = 2002,

		// Chat
		CS_Chat_Room_Request = 3001,
		SC_Chat_Room_Response = 3002,

		PROTO_TYPE_MAX,
	}; // ProtoType

	constexpr const char* ProtoTypeToString(const EProtoType value) {
		switch (value) {
			// Login
			case EProtoType::CS_LoginRequest: return "CS_LoginRequest";
			case EProtoType::SC_LoginResponse: return "SC_LoginResponse";
			case EProtoType::SC_OverrideLoginResponse: return "SC_OverrideLoginResponse";

			// Appearance
			case EProtoType::CS_AppearanceRequest: return "CS_AppearanceRequest";
			case EProtoType::SC_AppearanceResponse: return "SC_AppearanceResponse";

			// Chat
			case EProtoType::CS_Chat_Room_Request: return "CS_Chat_Room_Request";
			case EProtoType::SC_Chat_Room_Response: return "SC_Chat_Room_Response";

			default: return "UNDEFINED";
		} // switch
	}

} // protocol