/**
 * Protocol ID define here by enum class
 * This file is generated by Python script. Do not edit!!!
 * Python version: v3.12.7
 * Script version: v0.1
 */

#pragma once

#include <cstdint>

namespace protocol {
	enum class EProtoType : uint32_t {
		// Login
		CS_LoginRequest = 1001,
		SC_LoginResponse = 1002,
		SC_OverrideLoginResponse = 1003,

		PROTO_TYPE_MAX,
	}; // EProtoType

	constexpr const char* ProtoTypeToString(const EProtoType value) {
		switch (value) {
			// Login
			case EProtoType::CS_LoginRequest: return "CS_LoginRequest";
			case EProtoType::SC_LoginResponse: return "SC_LoginResponse";
			case EProtoType::SC_OverrideLoginResponse: return "SC_OverrideLoginResponse";

			default: return "UNDEFINED";
		} // switch
	}

} // protocol