/**
 * Protocol callback function define here.
 * This file is generated by Python script. Do not edit!!!
 * Python version: v3.12.7
 * Script version: v0.1
 */

#pragma once

#include <memory>
#include <asio/awaitable.hpp>

class IPackage;
class UCharacter;

using AConnectionPointer = std::shared_ptr<class UConnection>;
using asio::awaitable;

namespace protocol {

	// Login

	// Appearance
	awaitable<void> CS_AppearanceRequest(const std::shared_ptr<UCharacter> &plr, IPackage *pkg);

	// Chat
	awaitable<void> CS_ChatRoomRequest(const std::shared_ptr<UCharacter> &plr, IPackage *pkg);
	awaitable<void> CS_ChatToRoomRequest(const std::shared_ptr<UCharacter> &plr, IPackage *pkg);

} // protocol

#include "ProtoType.h"
#include "../base/system/protocol/ProtocolSystem.h"

inline void LoadProtocol(UProtocolSystem *sys) {

	using namespace protocol;

	// Login

	// Appearance
	REGISTER_PROTOCOL(CS_AppearanceRequest)

	// Chat
	REGISTER_PROTOCOL(CS_ChatRoomRequest)
	REGISTER_PROTOCOL(CS_ChatToRoomRequest)

}