/**
 * Protocol ID define here by enum class
 * This file is generated by Python script. Do not edit!!!
 * Python version: v3.12.7
 * Script version: v0.1
 */

#pragma once

#include <cstdint>

namespace protocol {
	enum class EProtoType : uint32_t {
		// Login
		CS_LoginRequest = 1001,
		SC_LoginResponse = 1002,
		SC_OverrideLoginResponse = 1003,

		// Appearance
		CS_AppearanceRequest = 2001,
		SC_AppearanceResponse = 2002,

		// Chat
		CS_ChatRoomRequest = 3001,
		SC_ChatRoomResponse = 3002,
		CS_ChatToRoomRequest = 3003,
		SC_ChatToRoomResponse = 3004,
		SC_OnChatRoomResponse = 3005,

		PROTO_TYPE_MAX,
	}; // EProtoType

	constexpr const char* ProtoTypeToString(const EProtoType value) {
		switch (value) {
			// Login
			case EProtoType::CS_LoginRequest: return "CS_LoginRequest";
			case EProtoType::SC_LoginResponse: return "SC_LoginResponse";
			case EProtoType::SC_OverrideLoginResponse: return "SC_OverrideLoginResponse";

			// Appearance
			case EProtoType::CS_AppearanceRequest: return "CS_AppearanceRequest";
			case EProtoType::SC_AppearanceResponse: return "SC_AppearanceResponse";

			// Chat
			case EProtoType::CS_ChatRoomRequest: return "CS_ChatRoomRequest";
			case EProtoType::SC_ChatRoomResponse: return "SC_ChatRoomResponse";
			case EProtoType::CS_ChatToRoomRequest: return "CS_ChatToRoomRequest";
			case EProtoType::SC_ChatToRoomResponse: return "SC_ChatToRoomResponse";
			case EProtoType::SC_OnChatRoomResponse: return "SC_OnChatRoomResponse";

			default: return "UNDEFINED";
		} // switch
	}

} // protocol