/**
 * Protocol callback function define here.
 * This file is generated by Python script. Do not edit!!!
 * Python version: v3.12.7
 * Script version: v0.1
 */

#pragma once

#include <asio.hpp>
#include <memory>

class IPackage;
using AConnectionPointer = std::shared_ptr<class UConnection>;
class IAbstractPlayer;

namespace protocol {

	 using asio::awaitable;

	// Login

	// Appearance
	void CS_AppearanceRequest(const std::shared_ptr<IAbstractPlayer> &plr, IPackage *pkg);

	// Chat
	void CS_ChatRoomRequest(const std::shared_ptr<IAbstractPlayer> &plr, IPackage *pkg);

} // protocol

#include "ProtoType.h"
#include "../base/system/protocol/ProtocolSystem.h"

inline void LoadProtocol(UProtocolSystem *sys) {

	using namespace protocol;

	// Login

	// Appearance
	REGISTER_PROTOCOL(CS_AppearanceRequest)

	// Chat
	REGISTER_PROTOCOL(CS_ChatRoomRequest)

}